services:
  remnawave-tg-shop:
    image: ghcr.io/machka-pasla/remnawave-tg-shop:latest
    container_name: remnawave-tg-shop
    hostname: remnawave-tg-shop
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - remnawave-network
    environment:
      - TZ=UTC
    volumes:
      - ./locales:/app/locales
    restart: unless-stopped
    depends_on:
      - remnawave-tg-shop-db
  remnawave-tg-shop-db:
    image: postgres:17
    container_name: remnawave-tg-shop-db
    hostname: remnawave-tg-shop-db
    env_file:
      - .env
    environment:
      - TZ=UTC
    volumes:
      - remnawave-tg-shop-db-data:/var/lib/postgresql/data
    networks:
      - remnawave-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20
networks:
  remnawave-network: null
volumes:
  remnawave-tg-shop-db-data:
    name: remnawave-tg-shop-db-data
